r64: add timer0 node which is missing in linux dts but required by uboot
Core:  99 devices, 21 uclasses, devicetree: separate
Could not initialize timer (err -19)

resetting ...

now state is this:

U-Boot 2024.07-rc1-bpi-ofupstream (May 25 2024 - 10:35:11 +0200)
CPU:   MediaTek MT7622
Model: Bananapi BPI-R64
DRAM:  dram_init ret: 0
dram_init...ram-base: 40000000, ram-size: 40000000
dram_init gd->ram_size 40000000
1 GiB
Core:  100 devices, 22 uclasses, devicetree: separate
MMC:   mmc@11230000: 0, mmc@11240000: 1
Loading Environment from nowhere... OK
In:    serial@11002000
Out:   serial@11002000
Err:   serial@11002000
Net:   error: Unable to get reset ctrl for frame engine
No ethernet found.
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc1 is current device
Boot from SD
621081b1-377b-41de-8cb3-7f98a9efa3a8
success!
181 bytes read in 3 ms (58.6 KiB/s)
mtk_sd mmc@11230000: phase: [map:87ffffff] [maxlen:27] [final:9]
mtk_sd mmc@11230000: Final pad delay: 9
No EFI system partition
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
error: Unable to get reset ctrl for frame engine
error: Unable to get reset ctrl for frame engine